/**
 * Per-registrar TLD support sets (without dots).
 * Porkbun is derived dynamically from their pricing API; these are curated from registrar data.
 * Shared between api-server.ts (local API mode) and client-side (browser/worker modes).
 */

/** Spaceship supported TLDs (470+, from spaceship.com) */
export const SPACESHIP_TLDS = [
	'abogado','ac','academy','accountant','accountants','actor','ad','adult','agency','ai',
	'airforce','apartments','app','archi','army','art','asia','associates','attorney','auction',
	'audio','auto','autos','baby','band','bar','barcelona','bargains','beauty','beer','best',
	'bet','bike','bingo','bio','biz','black','blackfriday','blog','blue','boats','bond','boo',
	'boston','bot','boutique','broker','build','builders','business','buzz','ca','cab','cafe',
	'cam','camera','camp','capital','car','cards','care','careers','cars','casa','cash','casino',
	'cat','catering','cc','center','ceo','cfd','channel','charity','chat','cheap','christmas',
	'church','city','claims','cleaning','click','clinic','clothing','cloud','club','co','coach',
	'codes','coffee','college','com','community','company','compare','computer','condos',
	'construction','consulting','contact','contractors','cooking','cool','country','coupons',
	'courses','credit','creditcard','cricket','cruises','cv','cymru','cyou','dad','dance','date',
	'dating','day','de','deal','dealer','deals','degree','delivery','democrat','dental','dentist',
	'design','dev','diamonds','diet','digital','direct','directory','discount','diy','doctor',
	'dog','domains','download','eco','education','email','energy','engineer','engineering',
	'enterprises','equipment','esq','estate','eu','events','exchange','expert','exposed','express',
	'fail','faith','family','fan','fans','farm','fashion','fast','feedback','finance','financial',
	'fish','fishing','fit','fitness','flights','florist','flowers','fm','foo','food','football',
	'forex','forsale','forum','foundation','free','fun','fund','furniture','futbol','fyi','gallery',
	'game','games','garden','gay','gg','gifts','gives','giving','glass','global','gmbh','gold',
	'golf','graphics','gratis','green','gripe','group','guide','guitars','guru','hair','haus',
	'health','healthcare','help','hiphop','hiv','hockey','holdings','holiday','homes','horse',
	'hospital','host','hosting','hot','house','how','icu','id','im','immo','immobilien','in',
	'inc','industries','info','ing','ink','institute','insure','international','investments','io',
	'irish','je','jetzt','jewelry','kaufen','kids','kim','kitchen','land','lat','law','lawyer',
	'lease','legal','lgbt','life','lifestyle','lighting','limited','limo','link','live','living',
	'llc','loan','loans','locker','lol','london','lotto','love','ltd','luxe','luxury','maison',
	'makeup','management','market','marketing','markets','mba','me','media','meme','memorial',
	'men','miami','mobi','mobile','moda','mom','money','monster','mortgage','motorcycles','mov',
	'movie','music','my','navy','net','network','new','news','nexus','ninja','now','nyc',
	'observer','one','online','org','page','partners','parts','party','pet','phd','photo',
	'photography','photos','pics','pictures','pink','pizza','place','plumbing','plus','poker',
	'porn','press','pro','productions','prof','promo','properties','property','protection','pub',
	'pw','quest','racing','realty','recipes','red','rehab','reise','reisen','rent','rentals',
	'repair','report','republican','rest','restaurant','review','reviews','rip','rocks','rodeo',
	'rsvp','run','sale','salon','sarl','sbs','school','schule','science','security','select',
	'services','sex','sexy','sh','shiksha','shoes','shop','shopping','show','singles','site',
	'ski','skin','soccer','social','software','solar','solutions','soy','space','spot','storage',
	'store','stream','studio','study','style','supplies','supply','support','surf','surgery',
	'systems','talk','tattoo','tax','taxi','team','tech','technology','tel','tennis','theater',
	'theatre','tickets','tienda','tips','tires','to','today','tools','top','tours','town','toys',
	'trade','trading','training','tv','uk','university','uno','us','vacations','vana','ventures',
	'vet','viajes','video','villas','vin','vip','vision','vodka','vote','voto','voyage','wales',
	'watch','webcam','website','wedding','wiki','win','wine','work','works','world','wtf','xxx',
	'xyz','yachts','yoga','you','zip','zone',
] as const;

/** Namecheap supported TLDs (520+, from namecheap.com) */
export const NAMECHEAP_TLDS = [
	'ac','academy','accountant','accountants','actor','ad','adult','africa','agency','ai',
	'airforce','apartments','app','archi','army','art','asia','associates','attorney','auction',
	'audio','auto','autos','baby','band','bar','barcelona','bargains','beauty','beer','berlin',
	'best','bet','bid','bike','bingo','bio','biz','black','blackfriday','blog','blue','boats',
	'bond','boo','boston','bot','boutique','broker','build','builders','business','buzz','bz','ca',
	'cab','cafe','cam','camera','camp','capital','car','cards','care','careers','cars','casa',
	'cash','casino','cat','catering','cc','center','ceo','cfd','ch','channel','charity','chat',
	'cheap','christmas','church','city','claims','cleaning','click','clinic','clothing','cloud',
	'club','cm','cn','co','coach','codes','coffee','college','com','community','company',
	'computer','condos','construction','consulting','contact','contractors','cooking','cool',
	'country','coupons','courses','credit','creditcard','cricket','cruises','cv','cx','cymru',
	'cyou','dad','dance','date','dating','day','de','deal','dealer','deals','degree','delivery',
	'democrat','dental','dentist','desi','design','dev','diamonds','diet','digital','direct',
	'directory','discount','diy','doctor','dog','domains','download','earth','eco','education',
	'email','energy','engineer','engineering','enterprises','equipment','es','esq','estate','eu',
	'events','exchange','expert','exposed','express','fail','faith','family','fan','fans','farm',
	'fashion','fast','feedback','film','finance','financial','fish','fishing','fit','fitness',
	'flights','florist','flowers','fm','foo','food','football','forex','forsale','forum',
	'foundation','fr','free','fun','fund','furniture','futbol','fyi','gallery','game','games',
	'garden','gay','gdn','gg','gift','gifts','gives','giving','glass','global','gmbh','gold',
	'golf','graphics','gratis','green','gripe','group','guide','guitars','guru','hair','hamburg',
	'haus','health','healthcare','help','hiphop','hockey','holdings','holiday','homes','horse',
	'hospital','host','hosting','hot','house','how','icu','id','im','immo','immobilien','in',
	'inc','industries','info','ing','ink','institute','insure','international','investments','io',
	'irish','is','jetzt','jewelry','juegos','kaufen','kids','kim','kitchen','kiwi','krd','kyoto',
	'la','land','lat','law','lawyer','lease','legal','lgbt','li','life','lifestyle','lighting',
	'limited','limo','link','live','living','llc','loan','loans','locker','lol','london','love',
	'ltd','ltda','luxury','maison','makeup','management','market','marketing','markets','mba',
	'me','media','melbourne','meme','memorial','men','menu','miami','mobi','mobile','moda','moe',
	'mom','money','monster','mortgage','motorcycles','mov','movie','music','mx','my','nagoya',
	'name','navy','net','network','new','news','nexus','ngo','ninja','nl','now','nu','nyc',
	'observer','okinawa','one','ong','onl','online','org','osaka','page','paris','partners',
	'parts','party','pe','pet','ph','phd','photo','photography','photos','pics','pictures','pink',
	'pizza','place','plumbing','plus','poker','porn','press','pro','productions','prof','promo',
	'properties','property','protection','pub','pw','quest','racing','realty','recipes','red',
	'rehab','reise','reisen','rent','rentals','repair','report','republican','rest','restaurant',
	'review','reviews','rip','rocks','rodeo','rsvp','run','ryukyu','sale','salon','sarl','sbs',
	'school','schule','science','security','services','sex','sexy','sg','sh','shiksha','shoes',
	'shop','shopping','show','singles','site','ski','skin','so','soccer','social','software',
	'solar','solutions','soy','space','spot','storage','store','stream','studio','study','style',
	'sucks','supplies','supply','support','surf','surgery','sydney','systems','talk','tattoo',
	'tax','taxi','team','tech','technology','tel','tennis','theater','theatre','tickets','tienda',
	'tips','tires','to','today','tokyo','tools','top','tours','town','toys','trade','trading',
	'training','travel','tube','tv','uk','university','uno','us','vacations','vana','vc','vegas',
	'ventures','vet','viajes','video','villas','vin','vip','vision','vodka','vote','voting',
	'voto','voyage','wales','watch','webcam','website','wedding','wiki','win','wine','work',
	'works','world','ws','wtf','xxx','xyz','yachts','yoga','yokohama','you','zip','zone',
] as const;

/** Cloudflare supported TLDs (350+, from cloudflare.com/tld-policies) */
export const CLOUDFLARE_TLDS = [
	'academy','accountant','accountants','actor','agency','airforce','apartments','app','army',
	'associates','attorney','auction','band','bar','bargains','beer','bet','bid','bike','bingo',
	'biz','black','blog','blue','boo','boston','boutique','broker','builders','business','ca',
	'cab','cafe','camera','camp','capital','cards','care','careers','casa','cash','casino',
	'catering','cc','center','ceo','chat','cheap','church','city','claims','cleaning','clinic',
	'clothing','cloud','club','co','coach','codes','coffee','college','com','community','company',
	'compare','computer','condos','construction','consulting','contact','contractors','cooking',
	'cool','coupons','credit','creditcard','cricket','cruises','dad','dance','date','dating',
	'day','deals','degree','delivery','democrat','dental','dentist','design','dev','diamonds',
	'digital','direct','directory','discount','doctor','dog','domains','download','education',
	'email','energy','engineer','engineering','enterprises','equipment','esq','estate','events',
	'exchange','expert','express','fail','faith','family','fans','farm','fashion','finance',
	'financial','fish','fishing','fit','fitness','flights','florist','fm','foo','football','forex',
	'forsale','foundation','fun','fund','furniture','futbol','fyi','gallery','games','garden',
	'gifts','gives','glass','gmbh','gold','golf','graphics','gratis','green','gripe','group',
	'guide','guru','haus','health','healthcare','hockey','holdings','holiday','horse','hospital',
	'host','house','how','immo','immobilien','inc','industries','info','ink','institute','insure',
	'international','investments','io','irish','jetzt','jewelry','kaufen','kim','kitchen','land',
	'lawyer','lease','legal','lgbt','life','lighting','limited','limo','link','live','loan',
	'loans','love','ltd','luxe','maison','management','market','marketing','markets','mba','me',
	'media','memorial','men','miami','mobi','moda','money','mortgage','mov','movie','mx','navy',
	'net','network','new','news','nexus','ninja','observer','one','online','org','page','partners',
	'parts','party','pet','phd','photography','photos','pictures','pink','pizza','place','plumbing',
	'plus','press','pro','productions','prof','promo','properties','pub','racing','realty',
	'recipes','red','rehab','reise','reisen','rent','rentals','repair','report','republican',
	'rest','restaurant','review','reviews','rip','rocks','rodeo','rsvp','run','sale','salon',
	'sarl','school','schule','science','security','select','services','shoes','shop','shopping',
	'show','singles','site','soccer','social','software','solar','solutions','soy','space',
	'storage','store','stream','studio','style','supplies','supply','support','surf','surgery',
	'systems','tax','taxi','team','tech','technology','tennis','theater','theatre','tienda','tips',
	'tires','today','tools','tours','town','toys','trade','trading','training','travel','tv','uk',
	'university','us','vacations','ventures','vet','viajes','video','villas','vin','vip','vision',
	'vodka','voyage','watch','webcam','website','wedding','wiki','win','wine','work','works',
	'world','wtf','xyz','yoga','zone',
] as const;
